import type { Sandbox } from "e2b"

export const CLOUDCODE_ENV_START = "# cloudcode:preset-env:start"
export const CLOUDCODE_ENV_END = "# cloudcode:preset-env:end"
export const CLOUDCODE_LEGACY_PRESET_ENV_PATH = "/tmp/cloudcode-preset-env.sh"
export const CLOUDCODE_PRESET_ENV_PATH =
  "/home/user/.codex/cloudcode-preset-env.sh"

export type SandboxPresetEnvVar = {
  name: string
  value: string
}

function envLocalPath(repoPath: string) {
  return `${repoPath}/.env.local`
}

function trimManagedBlock(content: string) {
  const pattern = new RegExp(
    `\\n?${escapeRegExp(CLOUDCODE_ENV_START)}[\\s\\S]*?${escapeRegExp(
      CLOUDCODE_ENV_END
    )}\\n?`,
    "g"
  )

  return content
    .replace(pattern, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function dotenvValue(value: string) {
  return JSON.stringify(value)
}

function managedEnvBlock(envVars: SandboxPresetEnvVar[]) {
  if (envVars.length === 0) return ""

  return [
    CLOUDCODE_ENV_START,
    "# Generated by Cloudcode from the selected sandbox preset.",
    ...envVars.map((envVar) => `${envVar.name}=${dotenvValue(envVar.value)}`),
    CLOUDCODE_ENV_END,
  ].join("\n")
}

async function readEnvLocal(sandbox: Sandbox, repoPath: string) {
  try {
    return await sandbox.files.read(envLocalPath(repoPath))
  } catch {
    return null
  }
}

async function writeEnvLocal(
  sandbox: Sandbox,
  repoPath: string,
  content: string | null
) {
  if (content === null || content.length === 0) {
    await sandbox.commands
      .run(`rm -f ${shellQuote(envLocalPath(repoPath))}`, { timeoutMs: 10_000 })
      .catch(() => undefined)
    return
  }

  await sandbox.files.write(
    envLocalPath(repoPath),
    content.endsWith("\n") ? content : `${content}\n`
  )
}

export async function writeCloudcodeEnvLocal(
  sandbox: Sandbox,
  repoPath: string,
  envVars: SandboxPresetEnvVar[]
) {
  const original = await readEnvLocal(sandbox, repoPath)
  const cleaned = trimManagedBlock(original ?? "")
  const block = managedEnvBlock(envVars)

  if (!block) {
    await writeEnvLocal(sandbox, repoPath, cleaned || null)
    return
  }

  await writeEnvLocal(
    sandbox,
    repoPath,
    [cleaned, block].filter(Boolean).join("\n\n")
  )
}

export async function withoutCloudcodeEnvLocal<T>(
  sandbox: Sandbox,
  repoPath: string,
  action: () => Promise<T>
) {
  const original = await readEnvLocal(sandbox, repoPath)
  const cleaned = original === null ? null : trimManagedBlock(original)
  const changed = original !== null && cleaned !== original.trimEnd()
  const runtimeEnv = await readFile(sandbox, CLOUDCODE_PRESET_ENV_PATH)

  if (changed) {
    await writeEnvLocal(sandbox, repoPath, cleaned || null)
  }
  await sandbox.commands
    .run(
      `rm -f ${shellQuote(CLOUDCODE_PRESET_ENV_PATH)} ${shellQuote(CLOUDCODE_LEGACY_PRESET_ENV_PATH)}`,
      {
        timeoutMs: 10_000,
      }
    )
    .catch(() => undefined)

  try {
    return await action()
  } finally {
    if (changed) {
      await writeEnvLocal(sandbox, repoPath, original)
    }
    if (runtimeEnv !== null) {
      await sandbox.files.write(CLOUDCODE_PRESET_ENV_PATH, runtimeEnv)
      await sandbox.commands
        .run(`chmod 600 ${shellQuote(CLOUDCODE_PRESET_ENV_PATH)}`, {
          timeoutMs: 10_000,
        })
        .catch(() => undefined)
    }
  }
}

async function readFile(sandbox: Sandbox, path: string) {
  try {
    return await sandbox.files.read(path)
  } catch {
    return null
  }
}

function shellQuote(value: string) {
  return `'${value.replace(/'/g, "'\\''")}'`
}
