import { shellQuote } from "./daytona-sandbox"

export const CLOUDCODE_ENV_START = "# cloudcode:preset-env:start"
export const CLOUDCODE_ENV_END = "# cloudcode:preset-env:end"
export const CLOUDCODE_LEGACY_PRESET_ENV_PATH = "/tmp/cloudcode-preset-env.sh"

const ENV_LINE_PATTERN = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/

export type SandboxEnvVar = {
  name: string
  value: string
}

export type SandboxPresetEnvVar = SandboxEnvVar

export type SandboxEnvTarget = {
  readTextFile: (path: string) => Promise<string>
  runCommand: (
    command: string,
    options?: { timeoutMs?: number }
  ) => Promise<{
    exitCode: number
    stderr: string
    stdout: string
  }>
  writeTextFile: (path: string, content: string) => Promise<void>
}

function envLocalPath(repoPath: string) {
  return `${repoPath}/.env.local`
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function trimManagedBlock(content: string) {
  const pattern = new RegExp(
    `\\n?${escapeRegExp(CLOUDCODE_ENV_START)}[\\s\\S]*?${escapeRegExp(
      CLOUDCODE_ENV_END
    )}\\n?`,
    "g"
  )

  return content
    .replace(pattern, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()
}

function dotenvValue(value: string) {
  return JSON.stringify(value)
}

function managedEnvBlock(envVars: SandboxPresetEnvVar[]) {
  if (envVars.length === 0) return ""

  return [
    CLOUDCODE_ENV_START,
    "# Generated by Cloudcode from the selected sandbox preset.",
    ...envVars.map((envVar) => `${envVar.name}=${dotenvValue(envVar.value)}`),
    CLOUDCODE_ENV_END,
  ].join("\n")
}

function managedEnvName(line: string) {
  return line.match(ENV_LINE_PATTERN)?.[1]
}

function removeManagedEnvVars(content: string, names: Set<string>) {
  const lines = content.split(/\r?\n/)
  const next: string[] = []
  let changed = false

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index]

    if (line !== CLOUDCODE_ENV_START) {
      next.push(line)
      continue
    }

    const endIndex = lines.indexOf(CLOUDCODE_ENV_END, index + 1)
    if (endIndex === -1) {
      next.push(...lines.slice(index))
      break
    }

    const body = lines.slice(index + 1, endIndex)
    const kept = body.filter((bodyLine) => {
      const name = managedEnvName(bodyLine)
      if (!name || !names.has(name)) return true
      changed = true
      return false
    })
    const hasEnvVars = kept.some((bodyLine) => managedEnvName(bodyLine))

    if (hasEnvVars) {
      next.push(CLOUDCODE_ENV_START, ...kept, CLOUDCODE_ENV_END)
    }

    index = endIndex
  }

  if (!changed) return content

  return next
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()
}

async function readFile(target: SandboxEnvTarget, path: string) {
  try {
    return await target.readTextFile(path)
  } catch {
    return null
  }
}

async function readEnvLocal(target: SandboxEnvTarget, repoPath: string) {
  return await readFile(target, envLocalPath(repoPath))
}

async function writeEnvLocal(
  target: SandboxEnvTarget,
  repoPath: string,
  content: string | null
) {
  if (content === null || content.length === 0) {
    await target
      .runCommand(`rm -f ${shellQuote(envLocalPath(repoPath))}`, {
        timeoutMs: 10_000,
      })
      .catch(() => undefined)
    return
  }

  await target.writeTextFile(
    envLocalPath(repoPath),
    content.endsWith("\n") ? content : `${content}\n`
  )
}

export async function writeCloudcodeEnvLocal(
  target: SandboxEnvTarget,
  repoPath: string,
  envVars: SandboxPresetEnvVar[]
) {
  const original = await readEnvLocal(target, repoPath)
  const cleaned = trimManagedBlock(original ?? "")
  const block = managedEnvBlock(envVars)
  const next = block ? [cleaned, block].filter(Boolean).join("\n\n") : cleaned

  if ((original ?? "").trimEnd() === next.trimEnd()) return

  await writeEnvLocal(target, repoPath, next || null)
}

export async function removeCloudcodeEnvLocalVars(
  target: SandboxEnvTarget,
  repoPath: string,
  names: string[]
) {
  const namesToRemove = new Set(
    names.map((name) => name.trim()).filter(Boolean)
  )
  if (namesToRemove.size === 0) return { changed: false }

  const original = await readEnvLocal(target, repoPath)
  if (original === null) return { changed: false }

  const next = removeManagedEnvVars(original, namesToRemove)
  if (original.trimEnd() === next.trimEnd()) return { changed: false }

  await writeEnvLocal(target, repoPath, next || null)
  return { changed: true }
}

export async function withoutCloudcodeEnvLocal<T>(
  target: SandboxEnvTarget,
  paths: {
    legacyPresetEnvPath?: string
    presetEnvPath: string
    repoPath: string
  },
  action: () => Promise<T>
) {
  const original = await readEnvLocal(target, paths.repoPath)
  const cleaned = original === null ? null : trimManagedBlock(original)
  const changed = original !== null && cleaned !== original.trimEnd()
  const runtimeEnv = await readFile(target, paths.presetEnvPath)
  const legacyPresetEnvPath =
    paths.legacyPresetEnvPath ?? CLOUDCODE_LEGACY_PRESET_ENV_PATH

  if (changed) {
    await writeEnvLocal(target, paths.repoPath, cleaned || null)
  }
  await target
    .runCommand(
      `rm -f ${shellQuote(paths.presetEnvPath)} ${shellQuote(legacyPresetEnvPath)}`,
      { timeoutMs: 10_000 }
    )
    .catch(() => undefined)

  try {
    return await action()
  } finally {
    if (changed) {
      await writeEnvLocal(target, paths.repoPath, original)
    }
    if (runtimeEnv !== null) {
      await target.writeTextFile(paths.presetEnvPath, runtimeEnv)
      await target
        .runCommand(`chmod 600 ${shellQuote(paths.presetEnvPath)}`, {
          timeoutMs: 10_000,
        })
        .catch(() => undefined)
    }
  }
}
