import { shellQuote } from "./daytona-sandbox"

export const CLOUDCODE_ENV_START = "# cloudcode:preset-env:start"
export const CLOUDCODE_ENV_END = "# cloudcode:preset-env:end"
export const CLOUDCODE_LEGACY_PRESET_ENV_PATH = "/tmp/cloudcode-preset-env.sh"

export type SandboxPresetEnvVar = {
  name: string
  value: string
}

export type SandboxEnvTarget = {
  readTextFile: (path: string) => Promise<string>
  runCommand: (command: string, options?: { timeoutMs?: number }) => Promise<{
    exitCode: number
    stderr: string
    stdout: string
  }>
  writeTextFile: (path: string, content: string) => Promise<void>
}

function envLocalPath(repoPath: string) {
  return `${repoPath}/.env.local`
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function trimManagedBlock(content: string) {
  const pattern = new RegExp(
    `\\n?${escapeRegExp(CLOUDCODE_ENV_START)}[\\s\\S]*?${escapeRegExp(
      CLOUDCODE_ENV_END
    )}\\n?`,
    "g"
  )

  return content
    .replace(pattern, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()
}

function dotenvValue(value: string) {
  return JSON.stringify(value)
}

function managedEnvBlock(envVars: SandboxPresetEnvVar[]) {
  if (envVars.length === 0) return ""

  return [
    CLOUDCODE_ENV_START,
    "# Generated by Cloudcode from the selected sandbox preset.",
    ...envVars.map((envVar) => `${envVar.name}=${dotenvValue(envVar.value)}`),
    CLOUDCODE_ENV_END,
  ].join("\n")
}

async function readFile(target: SandboxEnvTarget, path: string) {
  try {
    return await target.readTextFile(path)
  } catch {
    return null
  }
}

async function readEnvLocal(target: SandboxEnvTarget, repoPath: string) {
  return await readFile(target, envLocalPath(repoPath))
}

async function writeEnvLocal(
  target: SandboxEnvTarget,
  repoPath: string,
  content: string | null
) {
  if (content === null || content.length === 0) {
    await target
      .runCommand(`rm -f ${shellQuote(envLocalPath(repoPath))}`, {
        timeoutMs: 10_000,
      })
      .catch(() => undefined)
    return
  }

  await target.writeTextFile(
    envLocalPath(repoPath),
    content.endsWith("\n") ? content : `${content}\n`
  )
}

export async function writeCloudcodeEnvLocal(
  target: SandboxEnvTarget,
  repoPath: string,
  envVars: SandboxPresetEnvVar[]
) {
  const original = await readEnvLocal(target, repoPath)
  const cleaned = trimManagedBlock(original ?? "")
  const block = managedEnvBlock(envVars)

  if (!block) {
    await writeEnvLocal(target, repoPath, cleaned || null)
    return
  }

  await writeEnvLocal(
    target,
    repoPath,
    [cleaned, block].filter(Boolean).join("\n\n")
  )
}

export async function withoutCloudcodeEnvLocal<T>(
  target: SandboxEnvTarget,
  paths: {
    legacyPresetEnvPath?: string
    presetEnvPath: string
    repoPath: string
  },
  action: () => Promise<T>
) {
  const original = await readEnvLocal(target, paths.repoPath)
  const cleaned = original === null ? null : trimManagedBlock(original)
  const changed = original !== null && cleaned !== original.trimEnd()
  const runtimeEnv = await readFile(target, paths.presetEnvPath)
  const legacyPresetEnvPath =
    paths.legacyPresetEnvPath ?? CLOUDCODE_LEGACY_PRESET_ENV_PATH

  if (changed) {
    await writeEnvLocal(target, paths.repoPath, cleaned || null)
  }
  await target
    .runCommand(
      `rm -f ${shellQuote(paths.presetEnvPath)} ${shellQuote(legacyPresetEnvPath)}`,
      { timeoutMs: 10_000 }
    )
    .catch(() => undefined)

  try {
    return await action()
  } finally {
    if (changed) {
      await writeEnvLocal(target, paths.repoPath, original)
    }
    if (runtimeEnv !== null) {
      await target.writeTextFile(paths.presetEnvPath, runtimeEnv)
      await target
        .runCommand(`chmod 600 ${shellQuote(paths.presetEnvPath)}`, {
          timeoutMs: 10_000,
        })
        .catch(() => undefined)
    }
  }
}
