const CLOUDCODE_TOOL_DOCTOR_SCRIPT = [
  "#!/usr/bin/env bash",
  "set -e",
  'export PATH="/home/user/.cloudcode/bin:/home/user/.local/bin:/home/user/.local/share/mise/shims:$PATH"',
  'MANIFEST="/home/user/.cloudcode/tooling/manifest.txt"',
  'if [ "${1:-}" = "doctor" ]; then',
  '  if [ -s "$MANIFEST" ]; then',
  '    cat "$MANIFEST"',
  "  else",
  '    echo "No Smart Tooling manifest was written."',
  "  fi",
  "  exit 0",
  "fi",
  'echo "Usage: cloudcode-tool doctor" >&2',
  "exit 2",
].join("\n")

const RESET_EXEC_SCRIPT = [
  "#!/usr/bin/python3",
  "import os",
  "import signal",
  "import sys",
  "",
  "if len(sys.argv) < 2:",
  '    print("Usage: cloudcode-exec <command> [args...]", file=sys.stderr)',
  "    raise SystemExit(2)",
  "",
  "try:",
  "    signal.signal(signal.SIGCHLD, signal.SIG_DFL)",
  "except Exception:",
  "    pass",
  "",
  "os.execvpe(sys.argv[1], sys.argv[1:], os.environ)",
].join("\n")

const RESET_EXEC_FUNCTION = [
  'reset_exec() {',
  '  if [ -x /home/user/.cloudcode/bin/cloudcode-exec ] && [ -x /usr/bin/python3 ]; then',
  '    exec /home/user/.cloudcode/bin/cloudcode-exec "$@"',
  "  fi",
  '  exec "$@"',
  "}",
].join("\n")

const FLUTTER_WRAPPER_SCRIPT = [
  "#!/usr/bin/env bash",
  "trap - CHLD 2>/dev/null || true",
  RESET_EXEC_FUNCTION,
  'export FLUTTER_ROOT="${FLUTTER_ROOT:-/home/user/.cloudcode/flutter}"',
  'if [ ! -x "$FLUTTER_ROOT/bin/flutter" ]; then',
  '  echo "Flutter is not installed at $FLUTTER_ROOT." >&2',
  "  exit 127",
  "fi",
  'reset_exec "$FLUTTER_ROOT/bin/flutter" "$@"',
].join("\n")

const DART_WRAPPER_SCRIPT = [
  "#!/usr/bin/env bash",
  "trap - CHLD 2>/dev/null || true",
  RESET_EXEC_FUNCTION,
  'export FLUTTER_ROOT="${FLUTTER_ROOT:-/home/user/.cloudcode/flutter}"',
  'if [ -x "$FLUTTER_ROOT/bin/dart" ]; then',
  '  reset_exec "$FLUTTER_ROOT/bin/dart" "$@"',
  "fi",
  'if [ -x "$FLUTTER_ROOT/bin/cache/dart-sdk/bin/dart" ]; then',
  '  reset_exec "$FLUTTER_ROOT/bin/cache/dart-sdk/bin/dart" "$@"',
  "fi",
  'echo "Dart is not installed in $FLUTTER_ROOT." >&2',
  "exit 127",
].join("\n")

const BUN_WRAPPER_SCRIPT = [
  "#!/usr/bin/env bash",
  "trap - CHLD 2>/dev/null || true",
  RESET_EXEC_FUNCTION,
  "for candidate in /home/user/.bun/bin/bun /home/user/.local/share/mise/shims/bun /usr/local/bin/bun /usr/bin/bun; do",
  '  if [ -x "$candidate" ]; then',
  '    reset_exec "$candidate" "$@"',
  "  fi",
  "done",
  'echo "Bun is not installed." >&2',
  "exit 127",
].join("\n")

function commandWrapperScript(command: string) {
  const label = command[0].toUpperCase() + command.slice(1)
  return [
    "#!/usr/bin/env bash",
    "trap - CHLD 2>/dev/null || true",
    RESET_EXEC_FUNCTION,
    'SELF_DIR="/home/user/.cloudcode/bin"',
    'SEARCH_PATH="$(printf "%s" "$PATH" | tr ":" "\\n" | grep -vx "$SELF_DIR" | paste -sd: -)"',
    "exec_candidate() {",
    '  candidate_path="$1"',
    "  shift",
    `  if [ ${JSON.stringify(command)} = "node" ] && "$candidate_path" --experimental-strip-types -e "" >/dev/null 2>&1; then`,
    '    reset_exec "$candidate_path" --experimental-strip-types "$@"',
    "  fi",
    '  reset_exec "$candidate_path" "$@"',
    "}",
    "if command -v mise >/dev/null 2>&1; then",
    "  mise_node_root=\"$(mise where node 2>/dev/null || true)\"",
    '  if [ -n "$mise_node_root" ]; then',
    `    mise_candidate="$mise_node_root/bin/${command}"`,
    '    if [ -x "$mise_candidate" ]; then',
    '      exec_candidate "$mise_candidate" "$@"',
    "    fi",
    "  fi",
    `  for mise_candidate in /home/user/.local/share/mise/installs/node/*/bin/${command}; do`,
    '    if [ -x "$mise_candidate" ]; then',
    '      exec_candidate "$mise_candidate" "$@"',
    "    fi",
    "  done",
    "fi",
    `candidate="$(PATH="$SEARCH_PATH" command -v ${command} 2>/dev/null || true)"`,
    'if [ -n "$candidate" ] && [ -x "$candidate" ]; then',
    '  exec_candidate "$candidate" "$@"',
    "fi",
    `echo "${label} is not installed." >&2`,
    "exit 127",
  ].join("\n")
}

export function resetExecInstallScript() {
  return [
    "mkdir -p /home/user/.cloudcode/bin",
    "cat > /home/user/.cloudcode/bin/cloudcode-exec <<'CLOUDCODE_EXEC'",
    RESET_EXEC_SCRIPT,
    "CLOUDCODE_EXEC",
    "chmod +x /home/user/.cloudcode/bin/cloudcode-exec",
  ].join("\n")
}

export function flutterWrapperInstallScript() {
  return [
    resetExecInstallScript(),
    "mkdir -p /home/user/.cloudcode/bin",
    "cat > /home/user/.cloudcode/bin/flutter <<'CLOUDCODE_FLUTTER'",
    FLUTTER_WRAPPER_SCRIPT,
    "CLOUDCODE_FLUTTER",
    "cat > /home/user/.cloudcode/bin/dart <<'CLOUDCODE_DART'",
    DART_WRAPPER_SCRIPT,
    "CLOUDCODE_DART",
    "chmod +x /home/user/.cloudcode/bin/flutter /home/user/.cloudcode/bin/dart",
  ].join("\n")
}

export function bunWrapperInstallScript() {
  return [
    resetExecInstallScript(),
    "mkdir -p /home/user/.cloudcode/bin",
    "cat > /home/user/.cloudcode/bin/bun <<'CLOUDCODE_BUN'",
    BUN_WRAPPER_SCRIPT,
    "CLOUDCODE_BUN",
    "chmod +x /home/user/.cloudcode/bin/bun",
  ].join("\n")
}

export function nodeToolWrapperInstallScript() {
  return [
    resetExecInstallScript(),
    "mkdir -p /home/user/.cloudcode/bin",
    "cat > /home/user/.cloudcode/bin/node <<'CLOUDCODE_NODE'",
    commandWrapperScript("node"),
    "CLOUDCODE_NODE",
    "cat > /home/user/.cloudcode/bin/npm <<'CLOUDCODE_NPM'",
    commandWrapperScript("npm"),
    "CLOUDCODE_NPM",
    "cat > /home/user/.cloudcode/bin/pnpm <<'CLOUDCODE_PNPM'",
    commandWrapperScript("pnpm"),
    "CLOUDCODE_PNPM",
    "cat > /home/user/.cloudcode/bin/yarn <<'CLOUDCODE_YARN'",
    commandWrapperScript("yarn"),
    "CLOUDCODE_YARN",
    "chmod +x /home/user/.cloudcode/bin/node /home/user/.cloudcode/bin/npm /home/user/.cloudcode/bin/pnpm /home/user/.cloudcode/bin/yarn",
  ].join("\n")
}

export function smartToolingInstallScript() {
  return [
    "mkdir -p /home/user/.cloudcode/bin /home/user/.cloudcode/tooling /home/user/.config/mise",
    'export PATH="/home/user/.cloudcode/bin:/home/user/.local/bin:/home/user/.local/share/mise/shims:$PATH"',
    "trap - CHLD 2>/dev/null || true",
    'export MISE_YES=1',
    'export MISE_JOBS="${MISE_JOBS:-2}"',
    'export MISE_PYTHON_GITHUB_ATTESTATIONS=false',
    'export MISE_TRUSTED_CONFIG_PATHS="/home/user/repo"',
    'MANIFEST="/home/user/.cloudcode/tooling/manifest.txt"',
    "cd /home/user/repo",
    ': > "$MANIFEST"',
    'log_tooling() { echo "[smart-tooling] $*"; }',
    'record_tooling() { printf "%s\\n" "$*" >> "$MANIFEST"; }',
    'has_cmd() { command -v "$1" >/dev/null 2>&1; }',
    'first_line_version() { sed -n "1p" "$1" | tr -d "[:space:]" | sed "s/^v//"; }',
    'is_exact_version() { printf "%s" "$1" | grep -Eq "^v?[0-9]+([.][0-9]+){1,2}([-.+][A-Za-z0-9.]+)?$"; }',
    'version_key() { awk -F. \'{ printf "%03d%03d%03d\\n", $1, $2, $3 }\' <<< "$1"; }',
    'max_version() { if [ -z "$1" ]; then printf "%s\\n" "$2"; elif [ "$(version_key "$2")" -gt "$(version_key "$1")" ]; then printf "%s\\n" "$2"; else printf "%s\\n" "$1"; fi; }',
    "normalize_node_version() {",
    '  case "$1" in',
    '    *.*.*) printf "%s\\n" "$1" ;;',
    '    *.*) printf "%s.0\\n" "$1" ;;',
    '    *) printf "%s.0.0\\n" "$1" ;;',
    "  esac",
    "}",
    "node_engine_min_version() {",
    '  ENGINE_RANGE="$(printf "%s" "$1" | tr -d "\\n")"',
    '  CANDIDATE="$(printf "%s" "$ENGINE_RANGE" | sed -nE "s/.*>= *v?([0-9]+([.][0-9]+){0,2}).*/\\1/p" | head -n 1)"',
    '  if [ -z "$CANDIDATE" ]; then',
    '    CANDIDATE="$(printf "%s" "$ENGINE_RANGE" | sed -nE "s/.*[~^] *v?([0-9]+([.][0-9]+){0,2}).*/\\1/p" | head -n 1)"',
    "  fi",
    '  if [ -z "$CANDIDATE" ]; then',
    '    CANDIDATE="$(printf "%s" "$ENGINE_RANGE" | sed -nE "s/(^|.*[[:space:]])v?([0-9]+([.][0-9]+){0,2})([[:space:]].*|$)/\\2/p" | head -n 1)"',
    "  fi",
    '  if [ -n "$CANDIDATE" ]; then normalize_node_version "$CANDIDATE"; fi',
    "}",
    "find_manifest_files() {",
    "  find . -path './node_modules' -prune -o -path './.git' -prune -o -path './.next' -prune -o -path './dist' -prune -o -path './build' -prune -o -name package.json -print",
    "}",
    "find_repo_file() {",
    '  PATTERN="$1"',
    "  find . -path './node_modules' -prune -o -path './.git' -prune -o -path './.next' -prune -o -path './dist' -prune -o -path './build' -prune -o -name \"$PATTERN\" -print -quit",
    "}",
    "scan_package_manifests() {",
    '  PACKAGE_MANAGER=""',
    '  NODE_ENGINE_MIN=""',
    '  BUN_ENGINE_MIN=""',
    '  while IFS= read -r manifest; do',
    '    [ -f "$manifest" ] || continue',
    '    if [ -z "$PACKAGE_MANAGER" ]; then',
    '      MANAGER="$(json_value "$manifest" packageManager)"',
    '      if [ -n "$MANAGER" ]; then',
    '        PACKAGE_MANAGER="$MANAGER"',
    '        PACKAGE_MANAGER_SOURCE="$manifest packageManager"',
    "      fi",
    "    fi",
    '    if [ -z "$PACKAGE_MANAGER" ]; then',
    '      VOLTA_PNPM="$(json_value "$manifest" volta.pnpm)"',
    '      VOLTA_YARN="$(json_value "$manifest" volta.yarn)"',
    '      VOLTA_NPM="$(json_value "$manifest" volta.npm)"',
    '      if [ -n "$VOLTA_PNPM" ]; then PACKAGE_MANAGER="pnpm@$VOLTA_PNPM"; PACKAGE_MANAGER_SOURCE="$manifest volta.pnpm"; fi',
    '      if [ -z "$PACKAGE_MANAGER" ] && [ -n "$VOLTA_YARN" ]; then PACKAGE_MANAGER="yarn@$VOLTA_YARN"; PACKAGE_MANAGER_SOURCE="$manifest volta.yarn"; fi',
    '      if [ -z "$PACKAGE_MANAGER" ] && [ -n "$VOLTA_NPM" ]; then PACKAGE_MANAGER="npm@$VOLTA_NPM"; PACKAGE_MANAGER_SOURCE="$manifest volta.npm"; fi',
    "    fi",
    '    MANIFEST_NODE="$(json_value "$manifest" volta.node | sed "s/^v//")"',
    '    if [ -z "$MANIFEST_NODE" ]; then',
    '      NODE_ENGINE="$(json_value "$manifest" engines.node | sed "s/^v//")"',
    '      if [ -n "$NODE_ENGINE" ]; then',
    '        if is_exact_version "$NODE_ENGINE"; then MANIFEST_NODE="$NODE_ENGINE"; else MANIFEST_NODE="$(node_engine_min_version "$NODE_ENGINE")"; fi',
    "      fi",
    "    fi",
    '    if [ -n "$MANIFEST_NODE" ]; then',
    '      NODE_ENGINE_MIN="$(max_version "$NODE_ENGINE_MIN" "$MANIFEST_NODE")"',
    '      NODE_ENGINE_SOURCE="$manifest"',
    "    fi",
    '    MANIFEST_BUN=""',
    '    BUN_ENGINE="$(json_value "$manifest" engines.bun | sed "s/^v//")"',
    '    if [ -n "$BUN_ENGINE" ]; then',
    '      if is_exact_version "$BUN_ENGINE"; then MANIFEST_BUN="$BUN_ENGINE"; else MANIFEST_BUN="$(node_engine_min_version "$BUN_ENGINE")"; fi',
    '      if [ -n "$MANIFEST_BUN" ]; then BUN_ENGINE_MIN="$(max_version "$BUN_ENGINE_MIN" "$MANIFEST_BUN")"; BUN_ENGINE_SOURCE="$manifest engines.bun"; fi',
    "    fi",
    '  done < <(find_manifest_files)',
    "}",
    "write_json_reader() {",
    "  cat > /tmp/cloudcode-json-value.py <<'PY'",
    "import json",
    "import sys",
    "try:",
    "    with open(sys.argv[1], encoding=\"utf-8\") as f:",
    "        value = json.load(f)",
    "    for key in sys.argv[2].split(\".\"):",
    "        value = value[key]",
    "    if isinstance(value, (str, int, float)):",
    "        print(value)",
    "except Exception:",
    "    pass",
    "PY",
    "}",
    'json_value() { [ -f "$1" ] && has_cmd python3 && python3 /tmp/cloudcode-json-value.py "$1" "$2" 2>/dev/null || true; }',
    "ensure_mise() {",
    "  if ! has_cmd mise && [ ! -x /home/user/.local/bin/mise ]; then",
    '    log_tooling "Installing mise bootstrap"',
    "    curl https://mise.run | sh",
    "  fi",
    '  export PATH="/home/user/.local/bin:/home/user/.local/share/mise/shims:$PATH"',
    "  mkdir -p /home/user/.config/mise",
    '  export MISE_PYTHON_GITHUB_ATTESTATIONS=false',
    "  mise settings set python.github_attestations false || true",
    "  mise --version >/dev/null",
    "}",
    "install_mise_tool() {",
    '  TOOL_NAME="$1"',
    '  TOOL_VERSION="$2"',
    '  TOOL_SOURCE="$3"',
    '  if [ -z "$TOOL_VERSION" ]; then return 0; fi',
    "  ensure_mise",
    '  log_tooling "Installing $TOOL_NAME $TOOL_VERSION from $TOOL_SOURCE"',
    '  record_tooling "install $TOOL_NAME $TOOL_VERSION source=$TOOL_SOURCE"',
    '  mise use --global "$TOOL_NAME@$TOOL_VERSION"',
    '  if [ "$TOOL_NAME" = "bun" ]; then',
    bunWrapperInstallScript(),
    '    export PATH="/home/user/.cloudcode/bin:$PATH"',
    "  fi",
    '  if [ "$TOOL_NAME" = "node" ]; then',
    nodeToolWrapperInstallScript(),
    '    export PATH="/home/user/.cloudcode/bin:$PATH"',
    "  fi",
    "}",
    "install_package_manager() {",
    '  PACKAGE_SPEC="$1"',
    '  PACKAGE_SOURCE="$2"',
    '  PACKAGE_NAME="$(printf "%s" "$PACKAGE_SPEC" | cut -d@ -f1)"',
    '  PACKAGE_REQUESTED_VERSION="$(printf "%s" "$PACKAGE_SPEC" | cut -s -d@ -f2-)"',
    "  package_manager_path() {",
    "    if has_cmd mise; then",
    '      MISE_NODE_ROOT="$(mise where node 2>/dev/null || true)"',
    '      if [ -n "$MISE_NODE_ROOT" ]; then',
    '        MISE_PACKAGE_MANAGER="$MISE_NODE_ROOT/bin/$PACKAGE_NAME"',
    '        if [ -x "$MISE_PACKAGE_MANAGER" ]; then printf "%s\\n" "$MISE_PACKAGE_MANAGER"; return 0; fi',
    "      fi",
    '      for MISE_PACKAGE_MANAGER in /home/user/.local/share/mise/installs/node/*/bin/$PACKAGE_NAME; do',
    '        if [ -x "$MISE_PACKAGE_MANAGER" ]; then printf "%s\\n" "$MISE_PACKAGE_MANAGER"; return 0; fi',
    "      done",
    "    fi",
    '    SEARCH_PATH="$(printf "%s" "$PATH" | tr ":" "\\n" | grep -vx "/home/user/.cloudcode/bin" | paste -sd: -)"',
    '    PATH="$SEARCH_PATH" command -v "$PACKAGE_NAME" 2>/dev/null || true',
    "  }",
    "  package_manager_version_matches() {",
    '    if [ -z "$PACKAGE_REQUESTED_VERSION" ] || [ "$PACKAGE_REQUESTED_VERSION" = "latest" ]; then return 0; fi',
    '    if ! printf "%s" "$PACKAGE_REQUESTED_VERSION" | grep -Eq "^[0-9]+[.][0-9]+[.][0-9]+$"; then return 0; fi',
    '    ACTUAL_VERSION="$("$1" --version 2>/dev/null | head -n 1 | tr -d "[:space:]")"',
    '    [ "$ACTUAL_VERSION" = "$PACKAGE_REQUESTED_VERSION" ]',
    "  }",
    '  if has_cmd corepack; then',
    "    corepack enable || true",
    '    log_tooling "Activating $PACKAGE_SPEC through Corepack"',
    '    if corepack prepare "$PACKAGE_SPEC" --activate; then',
    '      PACKAGE_MANAGER_BIN="$(package_manager_path)"',
    '      if [ -n "$PACKAGE_MANAGER_BIN" ] && package_manager_version_matches "$PACKAGE_MANAGER_BIN"; then',
    '        record_tooling "activate $PACKAGE_SPEC source=$PACKAGE_SOURCE"',
    "        return 0",
    "      fi",
    '      record_tooling "fallback $PACKAGE_SPEC reason=corepack-did-not-install-binary"',
    "    else",
    '      record_tooling "fallback $PACKAGE_SPEC reason=corepack-prepare-failed"',
    "    fi",
    "  fi",
    "  if has_cmd npm; then",
    '    log_tooling "Installing $PACKAGE_SPEC through npm"',
    '    if [ -n "$PACKAGE_NAME" ]; then',
    '      rm -f "$(npm bin -g 2>/dev/null)/$PACKAGE_NAME" 2>/dev/null || true',
    '      REAL_NODE="$(PATH="$(printf "%s" "$PATH" | tr ":" "\\n" | grep -vx "/home/user/.cloudcode/bin" | paste -sd: -)" command -v node 2>/dev/null || true)"',
    '      if has_cmd mise; then REAL_NODE="$(mise where node 2>/dev/null)/bin/node"; fi',
    '      if [ -n "$REAL_NODE" ]; then rm -f "$(dirname "$REAL_NODE")/$PACKAGE_NAME" 2>/dev/null || true; fi',
    "    fi",
    '    npm install -g --force "$PACKAGE_SPEC"',
    "    mise reshim || true",
    '    PACKAGE_MANAGER_BIN="$(package_manager_path)"',
    '    if [ -z "$PACKAGE_MANAGER_BIN" ] || ! package_manager_version_matches "$PACKAGE_MANAGER_BIN"; then',
    '      echo "$PACKAGE_NAME is not installed after attempting $PACKAGE_SPEC." >&2',
    "      exit 127",
    "    fi",
    '    "$PACKAGE_MANAGER_BIN" --version >/dev/null',
    '    record_tooling "install $PACKAGE_SPEC source=$PACKAGE_SOURCE"',
    "  else",
    '    record_tooling "defer $PACKAGE_SPEC reason=npm-unavailable"',
    "  fi",
    "}",
    "install_flutter_tool() {",
    '  FLUTTER_VERSION="$1"',
    '  FLUTTER_SOURCE="$2"',
    '  if [ -z "$FLUTTER_VERSION" ]; then return 0; fi',
    '  log_tooling "Installing Flutter $FLUTTER_VERSION from $FLUTTER_SOURCE"',
    '  record_tooling "install flutter $FLUTTER_VERSION source=$FLUTTER_SOURCE"',
    "  mkdir -p /home/user/.cloudcode",
    "  if [ ! -d /home/user/.cloudcode/flutter/.git ]; then",
    '    git clone --depth 1 --branch "$FLUTTER_VERSION" https://github.com/flutter/flutter.git /home/user/.cloudcode/flutter || git clone --depth 1 --branch stable https://github.com/flutter/flutter.git /home/user/.cloudcode/flutter',
    "  else",
    "    git -C /home/user/.cloudcode/flutter fetch --depth 1 origin \"$FLUTTER_VERSION\" || git -C /home/user/.cloudcode/flutter fetch --depth 1 origin stable",
    '    git -C /home/user/.cloudcode/flutter checkout "$FLUTTER_VERSION" || git -C /home/user/.cloudcode/flutter checkout stable',
    "  fi",
    flutterWrapperInstallScript(),
    '  export PATH="/home/user/.cloudcode/bin:/home/user/.cloudcode/flutter/bin:$PATH"',
    "  flutter --version",
    "}",
    "write_cloudcode_tool() {",
    "  cat > /home/user/.cloudcode/bin/cloudcode-tool <<'CLOUDCODE_TOOL'",
    CLOUDCODE_TOOL_DOCTOR_SCRIPT,
    "CLOUDCODE_TOOL",
    "  chmod +x /home/user/.cloudcode/bin/cloudcode-tool",
    "}",
    "write_cloudcode_tool",
    "write_json_reader",
    'log_tooling "Inspecting repo tool signals"',
    'record_tooling "repo /home/user/repo"',
    "if [ -f mise.toml ] || [ -f .mise.toml ] || [ -f .tool-versions ]; then",
    "  ensure_mise",
    '  log_tooling "Installing tools declared by mise/.tool-versions"',
    '  record_tooling "install mise-declared-tools source=mise-or-tool-versions"',
    "  env -u MISE_TRUSTED_CONFIG_PATHS mise trust -a || true",
    "  mise install",
    "else",
    '  record_tooling "skip mise-declared-tools reason=no-mise-config"',
    "fi",
    'PACKAGE_MANAGER=""',
    'PACKAGE_MANAGER_SOURCE=""',
    'NODE_ENGINE_MIN=""',
    'NODE_ENGINE_SOURCE=""',
    'BUN_ENGINE_MIN=""',
    'BUN_ENGINE_SOURCE=""',
    "scan_package_manifests",
    'NODE_VERSION=""',
    'NODE_SOURCE=""',
    "if [ -f .node-version ]; then",
    '  NODE_VERSION="$(first_line_version .node-version)"',
    '  NODE_SOURCE=".node-version"',
    "elif [ -f .nvmrc ]; then",
    '  NODE_VERSION="$(first_line_version .nvmrc)"',
    '  NODE_SOURCE=".nvmrc"',
    "fi",
    "if [ -z \"$NODE_VERSION\" ] && [ -n \"$NODE_ENGINE_MIN\" ]; then",
    '  NODE_VERSION="$NODE_ENGINE_MIN"',
    '  NODE_SOURCE="${NODE_ENGINE_SOURCE:-package manifests}"',
    "fi",
    'if [ -n "$NODE_VERSION" ]; then',
    '  install_mise_tool node "$NODE_VERSION" "$NODE_SOURCE"',
    "else",
    '  record_tooling "skip node reason=no-exact-node-version"',
    "fi",
    'if [ -n "$PACKAGE_MANAGER" ]; then',
    '  log_tooling "Detected package manager $PACKAGE_MANAGER"',
    '  record_tooling "detect package-manager $PACKAGE_MANAGER source=${PACKAGE_MANAGER_SOURCE:-package manifests}"',
    '  PM_NAME="$(printf "%s" "$PACKAGE_MANAGER" | cut -d@ -f1)"',
    '  PM_VERSION="$(printf "%s" "$PACKAGE_MANAGER" | cut -s -d@ -f2-)"',
    '  case "$PM_NAME" in',
    "    bun)",
    '      if [ -n "$PM_VERSION" ]; then',
    '        install_mise_tool bun "$PM_VERSION" "package.json packageManager"',
    '      elif [ -n "$BUN_ENGINE_MIN" ]; then',
    '        install_mise_tool bun "$BUN_ENGINE_MIN" "${BUN_ENGINE_SOURCE:-engines.bun}"',
    "      elif has_cmd bun; then",
    bunWrapperInstallScript(),
    '        export PATH="/home/user/.cloudcode/bin:$PATH"',
    '        record_tooling "use bun $(bun --version) source=existing"',
    "      else",
    '        install_mise_tool bun latest "package.json packageManager"',
    "      fi",
    "      ;;",
    "    pnpm|yarn)",
    '      if [ -n "$PM_VERSION" ]; then PACKAGE_SPEC="$PACKAGE_MANAGER"; else PACKAGE_SPEC="$PM_NAME@latest"; fi',
    '      install_package_manager "$PACKAGE_SPEC" "${PACKAGE_MANAGER_SOURCE:-package manifests}"',
    "      ;;",
    "    npm)",
    '      if [ -n "$PM_VERSION" ] && has_cmd npm; then',
    '        log_tooling "Activating npm $PM_VERSION"',
    '        npm install -g "npm@$PM_VERSION"',
    '        record_tooling "install npm $PM_VERSION source=package.json"',
    "      else",
    '        record_tooling "use npm source=existing-or-node-default"',
    "      fi",
    "      ;;",
    "    *)",
    '      record_tooling "defer $PM_NAME reason=unsupported-package-manager"',
    "      ;;",
    "  esac",
    "else",
    "  if [ -f bun.lock ] || [ -f bun.lockb ]; then",
    '    install_mise_tool bun latest "bun lockfile"',
    "  elif [ -f pnpm-lock.yaml ]; then",
    '    install_package_manager pnpm@latest "pnpm-lock.yaml"',
    "  elif [ -f yarn.lock ]; then",
    '    install_package_manager yarn@latest "yarn.lock"',
    "  elif [ -f package-lock.json ]; then",
    '    record_tooling "use npm reason=package-lock"',
    "  else",
    '    if [ -n "$BUN_ENGINE_MIN" ]; then',
    '      install_mise_tool bun "$BUN_ENGINE_MIN" "${BUN_ENGINE_SOURCE:-engines.bun}"',
    "    else",
    '      record_tooling "skip package-manager reason=no-package-manager-signal"',
    "    fi",
    "  fi",
    "fi",
    'PYTHON_VERSION_FILE="$(find_repo_file .python-version)"',
    'PYPROJECT_FILE="$(find_repo_file pyproject.toml)"',
    'RUNTIME_FILE="$(find_repo_file runtime.txt)"',
    'if [ -n "$PYTHON_VERSION_FILE" ]; then',
    '  PYTHON_VERSION="$(first_line_version "$PYTHON_VERSION_FILE")"',
    '  install_mise_tool python "$PYTHON_VERSION" "$PYTHON_VERSION_FILE"',
    "elif [ -f runtime.txt ]; then",
    '  PYTHON_VERSION="$(sed -n "s/^python-//p" runtime.txt | head -n1 | tr -d "[:space:]")"',
    '  if [ -n "$PYTHON_VERSION" ]; then',
    '    install_mise_tool python "$PYTHON_VERSION" "runtime.txt"',
    "  else",
    '    record_tooling "defer python reason=runtime-txt-without-python-version"',
    "  fi",
    "elif [ -n \"$RUNTIME_FILE\" ]; then",
    '  PYTHON_VERSION="$(sed -n "s/^python-//p" "$RUNTIME_FILE" | head -n1 | tr -d "[:space:]")"',
    '  if [ -n "$PYTHON_VERSION" ]; then',
    '    install_mise_tool python "$PYTHON_VERSION" "$RUNTIME_FILE"',
    "  else",
    '    record_tooling "defer python reason=runtime-txt-without-python-version"',
    "  fi",
    "elif [ -n \"$PYPROJECT_FILE\" ]; then",
    '  PYTHON_RANGE="$(awk -F= \'/^[[:space:]]*requires-python[[:space:]]*=/{gsub(/[[:space:]\\"\\047]/, "", $2); print $2; exit}\' "$PYPROJECT_FILE")"',
    '  if printf "%s" "$PYTHON_RANGE" | grep -Eq "^==v?[0-9]+([.][0-9]+){1,2}$"; then',
    '    PYTHON_VERSION="$(printf "%s" "$PYTHON_RANGE" | sed "s/^==//; s/^v//")"',
    '    install_mise_tool python "$PYTHON_VERSION" "$PYPROJECT_FILE requires-python"',
    "  elif [ -n \"$PYTHON_RANGE\" ]; then",
    '    record_tooling "defer python $PYTHON_RANGE reason=requires-python-range"',
    "  else",
    '    record_tooling "defer python reason=pyproject-without-exact-python-version"',
    "  fi",
    "fi",
    'GO_VERSION_FILE="$(find_repo_file .go-version)"',
    'GOENV_VERSION_FILE="$(find_repo_file .goenv-version)"',
    'GO_MOD_FILE="$(find_repo_file go.mod)"',
    'if [ -n "$GO_VERSION_FILE" ]; then',
    '  GO_VERSION="$(first_line_version "$GO_VERSION_FILE")"',
    '  install_mise_tool go "$GO_VERSION" "$GO_VERSION_FILE"',
    "elif [ -n \"$GOENV_VERSION_FILE\" ]; then",
    '  GO_VERSION="$(first_line_version "$GOENV_VERSION_FILE")"',
    '  install_mise_tool go "$GO_VERSION" "$GOENV_VERSION_FILE"',
    "elif [ -n \"$GO_MOD_FILE\" ]; then",
    "  GO_VERSION=$(awk '/^toolchain go[0-9]/{sub(/^go/, \"\", $2); print $2; exit} /^go [0-9]/{print $2; exit}' \"$GO_MOD_FILE\")",
    '  install_mise_tool go "$GO_VERSION" "$GO_MOD_FILE"',
    "fi",
    'RUST_TOOLCHAIN_TOML="$(find_repo_file rust-toolchain.toml)"',
    'RUST_TOOLCHAIN_FILE="$(find_repo_file rust-toolchain)"',
    'CARGO_TOML_FILE="$(find_repo_file Cargo.toml)"',
    "if [ -n \"$RUST_TOOLCHAIN_TOML\" ]; then",
    "  RUST_VERSION=$(awk -F= '/^[[:space:]]*channel[[:space:]]*=/{gsub(/[[:space:]\"\\047]/, \"\", $2); print $2; exit}' \"$RUST_TOOLCHAIN_TOML\")",
    '  install_mise_tool rust "$RUST_VERSION" "$RUST_TOOLCHAIN_TOML"',
    "elif [ -n \"$RUST_TOOLCHAIN_FILE\" ]; then",
    '  RUST_VERSION="$(first_line_version "$RUST_TOOLCHAIN_FILE")"',
    '  install_mise_tool rust "$RUST_VERSION" "$RUST_TOOLCHAIN_FILE"',
    "elif [ -n \"$CARGO_TOML_FILE\" ]; then",
    '  record_tooling "defer rust reason=Cargo.toml-without-rust-toolchain"',
    "fi",
    'RUBY_VERSION_FILE="$(find_repo_file .ruby-version)"',
    'GEMFILE="$(find_repo_file Gemfile)"',
    "if [ -n \"$RUBY_VERSION_FILE\" ]; then",
    '  RUBY_VERSION="$(first_line_version "$RUBY_VERSION_FILE")"',
    '  install_mise_tool ruby "$RUBY_VERSION" "$RUBY_VERSION_FILE"',
    "elif [ -n \"$GEMFILE\" ]; then",
    "  RUBY_VERSION=$(awk '/^[[:space:]]*ruby[[:space:]]+\"[0-9]/{gsub(/[\",]/, \"\", $2); print $2; exit}' \"$GEMFILE\")",
    '  if [ -n "$RUBY_VERSION" ]; then',
    '    install_mise_tool ruby "$RUBY_VERSION" "$GEMFILE ruby"',
    "  else",
    '    record_tooling "defer ruby reason=Gemfile-without-ruby-version"',
    "  fi",
    "fi",
    'JAVA_VERSION_FILE="$(find_repo_file .java-version)"',
    'SDKMAN_FILE="$(find_repo_file .sdkmanrc)"',
    'POM_FILE="$(find_repo_file pom.xml)"',
    'GRADLE_FILE="$(find_repo_file build.gradle)"',
    'GRADLE_KTS_FILE="$(find_repo_file build.gradle.kts)"',
    "if [ -n \"$JAVA_VERSION_FILE\" ]; then",
    '  JAVA_VERSION="$(first_line_version "$JAVA_VERSION_FILE")"',
    '  install_mise_tool java "$JAVA_VERSION" "$JAVA_VERSION_FILE"',
    "elif [ -n \"$SDKMAN_FILE\" ]; then",
    "  JAVA_VERSION=$(awk -F= '/^java=/{print $2; exit}' \"$SDKMAN_FILE\")",
    '  if [ -n "$JAVA_VERSION" ]; then',
    '    install_mise_tool java "$JAVA_VERSION" "$SDKMAN_FILE"',
    "  elif [ -n \"$POM_FILE$GRADLE_FILE$GRADLE_KTS_FILE\" ]; then",
    '    record_tooling "defer java reason=jvm-project-without-java-version"',
    "  fi",
    "elif [ -n \"$POM_FILE$GRADLE_FILE$GRADLE_KTS_FILE\" ]; then",
    '  record_tooling "defer java reason=jvm-project-without-java-version"',
    "fi",
    'GLOBAL_JSON="$(find_repo_file global.json)"',
    'SLN_FILE="$(find_repo_file "*.sln")"',
    'CSPROJ_FILE="$(find_repo_file "*.csproj")"',
    "if [ -n \"$GLOBAL_JSON\" ]; then",
    '  DOTNET_VERSION="$(json_value "$GLOBAL_JSON" sdk.version)"',
    '  if [ -n "$DOTNET_VERSION" ]; then',
    '    install_mise_tool dotnet "$DOTNET_VERSION" "$GLOBAL_JSON sdk.version"',
    "  fi",
    "elif [ -n \"$SLN_FILE$CSPROJ_FILE\" ]; then",
    '  record_tooling "defer dotnet reason=dotnet-project-without-global-json"',
    "fi",
    'TERRAFORM_VERSION_FILE="$(find_repo_file .terraform-version)"',
    'TF_FILE="$(find_repo_file "*.tf")"',
    "if [ -n \"$TERRAFORM_VERSION_FILE\" ]; then",
    '  TERRAFORM_VERSION="$(first_line_version "$TERRAFORM_VERSION_FILE")"',
    '  install_mise_tool terraform "$TERRAFORM_VERSION" "$TERRAFORM_VERSION_FILE"',
    "elif [ -n \"$TF_FILE\" ]; then",
    '  record_tooling "defer terraform reason=terraform-files-without-terraform-version"',
    "fi",
    'TOFU_VERSION_FILE="$(find_repo_file .tofu-version)"',
    "if [ -n \"$TOFU_VERSION_FILE\" ]; then",
    '  TOFU_VERSION="$(first_line_version "$TOFU_VERSION_FILE")"',
    '  install_mise_tool opentofu "$TOFU_VERSION" "$TOFU_VERSION_FILE"',
    "fi",
    'FVMRC_FILE="$(find_repo_file .fvmrc)"',
    'PUBSPEC_FILE="$(find_repo_file pubspec.yaml)"',
    "if [ -n \"$FVMRC_FILE\" ]; then",
    '  FLUTTER_VERSION="$(json_value "$FVMRC_FILE" flutter)"',
    '  if [ -z "$FLUTTER_VERSION" ]; then FLUTTER_VERSION="$(first_line_version "$FVMRC_FILE")"; fi',
    '  if [ -n "$FLUTTER_VERSION" ]; then',
    '    install_flutter_tool "$FLUTTER_VERSION" "$FVMRC_FILE"',
    "  else",
    '    record_tooling "defer flutter reason=fvmrc-without-version"',
    "  fi",
    "elif [ -n \"$PUBSPEC_FILE\" ]; then",
    '  install_flutter_tool stable "$PUBSPEC_FILE"',
    "fi",
    'ZIG_VERSION_FILE="$(find_repo_file .zig-version)"',
    'BUILD_ZIG="$(find_repo_file build.zig)"',
    'BUILD_ZON="$(find_repo_file build.zig.zon)"',
    "if [ -n \"$ZIG_VERSION_FILE\" ]; then",
    '  ZIG_VERSION="$(first_line_version "$ZIG_VERSION_FILE")"',
    '  install_mise_tool zig "$ZIG_VERSION" "$ZIG_VERSION_FILE"',
    "elif [ -n \"$BUILD_ZIG$BUILD_ZON\" ]; then",
    '  record_tooling "defer zig reason=zig-project-without-zig-version"',
    "fi",
    'SWIFT_VERSION_FILE="$(find_repo_file .swift-version)"',
    'PACKAGE_SWIFT="$(find_repo_file Package.swift)"',
    "if [ -n \"$SWIFT_VERSION_FILE\" ]; then",
    '  SWIFT_VERSION="$(first_line_version "$SWIFT_VERSION_FILE")"',
    '  record_tooling "defer swift $SWIFT_VERSION reason=requires-platform-specific-toolchain-url"',
    "elif [ -n \"$PACKAGE_SWIFT\" ]; then",
    '  record_tooling "defer swift reason=Package.swift-without-swift-version"',
    "fi",
    'PHP_VERSION_FILE="$(find_repo_file .php-version)"',
    'COMPOSER_JSON="$(find_repo_file composer.json)"',
    "if [ -n \"$PHP_VERSION_FILE\" ]; then",
    '  PHP_VERSION="$(first_line_version "$PHP_VERSION_FILE")"',
    '  record_tooling "defer php $PHP_VERSION reason=system-dependencies"',
    "elif [ -n \"$COMPOSER_JSON\" ]; then",
    '  record_tooling "defer php reason=composer-json-without-php-version"',
    "fi",
    'DENO_VERSION_FILE="$(find_repo_file .deno-version)"',
    'DENO_JSON="$(find_repo_file deno.json)"',
    'DENO_JSONC="$(find_repo_file deno.jsonc)"',
    "if [ -n \"$DENO_VERSION_FILE\" ]; then",
    '  DENO_VERSION="$(first_line_version "$DENO_VERSION_FILE")"',
    '  install_mise_tool deno "$DENO_VERSION" "$DENO_VERSION_FILE"',
    "elif [ -n \"$DENO_JSON$DENO_JSONC\" ]; then",
    '  install_mise_tool deno latest "deno config"',
    "fi",
    'NIX_FILE="$(find_repo_file flake.nix)"',
    'if [ -z "$NIX_FILE" ]; then NIX_FILE="$(find_repo_file shell.nix)"; fi',
    'if [ -z "$NIX_FILE" ]; then NIX_FILE="$(find_repo_file default.nix)"; fi',
    "if [ -n \"$NIX_FILE\" ]; then",
    '  record_tooling "defer nix reason=nix-environment-detected"',
    "fi",
    'DEVCONTAINER_FILE="$(find . -path "./node_modules" -prune -o -path "./.git" -prune -o -path "*/.devcontainer/devcontainer.json" -print -quit)"',
    "if [ -n \"$DEVCONTAINER_FILE\" ]; then",
    '  record_tooling "defer devcontainer reason=devcontainer-detected"',
    "fi",
    "if has_cmd mise; then mise reshim || true; fi",
    'log_tooling "Smart Tooling ready"',
    "cloudcode-tool doctor || true",
  ].join("\n")
}
