const CLOUDCODE_TOOL_DOCTOR_SCRIPT = [
  "#!/usr/bin/env bash",
  "set -e",
  'export PATH="/home/user/.cloudcode/bin:/home/user/.local/bin:/home/user/.local/share/mise/shims:$PATH"',
  'MANIFEST="/home/user/.cloudcode/tooling/manifest.txt"',
  'if [ "${1:-}" = "doctor" ]; then',
  '  if [ -s "$MANIFEST" ]; then',
  '    cat "$MANIFEST"',
  "  else",
  '    echo "No Smart Tooling manifest was written."',
  "  fi",
  "  exit 0",
  "fi",
  'echo "Usage: cloudcode-tool doctor" >&2',
  "exit 2",
].join("\n")

export function smartToolingInstallScript() {
  return [
    "mkdir -p /home/user/.cloudcode/bin /home/user/.cloudcode/tooling /home/user/.config/mise",
    'export PATH="/home/user/.cloudcode/bin:/home/user/.local/bin:/home/user/.local/share/mise/shims:$PATH"',
    'export MISE_YES=1',
    'export MISE_JOBS="${MISE_JOBS:-2}"',
    'export MISE_TRUSTED_CONFIG_PATHS="/home/user/repo"',
    'MANIFEST="/home/user/.cloudcode/tooling/manifest.txt"',
    "cd /home/user/repo",
    ': > "$MANIFEST"',
    'log_tooling() { echo "[smart-tooling] $*"; }',
    'record_tooling() { printf "%s\\n" "$*" >> "$MANIFEST"; }',
    'has_cmd() { command -v "$1" >/dev/null 2>&1; }',
    'first_line_version() { sed -n "1p" "$1" | tr -d "[:space:]" | sed "s/^v//"; }',
    'is_exact_version() { printf "%s" "$1" | grep -Eq "^v?[0-9]+([.][0-9]+){1,2}([-.+][A-Za-z0-9.]+)?$"; }',
    "write_json_reader() {",
    "  cat > /tmp/cloudcode-json-value.py <<'PY'",
    "import json",
    "import sys",
    "try:",
    "    with open(sys.argv[1], encoding=\"utf-8\") as f:",
    "        value = json.load(f)",
    "    for key in sys.argv[2].split(\".\"):",
    "        value = value[key]",
    "    if isinstance(value, (str, int, float)):",
    "        print(value)",
    "except Exception:",
    "    pass",
    "PY",
    "}",
    'json_value() { [ -f "$1" ] && has_cmd python3 && python3 /tmp/cloudcode-json-value.py "$1" "$2" 2>/dev/null || true; }',
    "ensure_mise() {",
    "  if ! has_cmd mise && [ ! -x /home/user/.local/bin/mise ]; then",
    '    log_tooling "Installing mise bootstrap"',
    "    curl https://mise.run | sh",
    "  fi",
    '  export PATH="/home/user/.local/bin:/home/user/.local/share/mise/shims:$PATH"',
    "  mise --version >/dev/null",
    "}",
    "install_mise_tool() {",
    '  TOOL_NAME="$1"',
    '  TOOL_VERSION="$2"',
    '  TOOL_SOURCE="$3"',
    '  if [ -z "$TOOL_VERSION" ]; then return 0; fi',
    "  ensure_mise",
    '  log_tooling "Installing $TOOL_NAME $TOOL_VERSION from $TOOL_SOURCE"',
    '  record_tooling "install $TOOL_NAME $TOOL_VERSION source=$TOOL_SOURCE"',
    '  mise use --global "$TOOL_NAME@$TOOL_VERSION"',
    "}",
    "write_cloudcode_tool() {",
    "  cat > /home/user/.cloudcode/bin/cloudcode-tool <<'CLOUDCODE_TOOL'",
    CLOUDCODE_TOOL_DOCTOR_SCRIPT,
    "CLOUDCODE_TOOL",
    "  chmod +x /home/user/.cloudcode/bin/cloudcode-tool",
    "}",
    "write_cloudcode_tool",
    "write_json_reader",
    'log_tooling "Inspecting repo tool signals"',
    'record_tooling "repo /home/user/repo"',
    "if [ -f mise.toml ] || [ -f .mise.toml ] || [ -f .tool-versions ]; then",
    "  ensure_mise",
    '  log_tooling "Installing tools declared by mise/.tool-versions"',
    '  record_tooling "install mise-declared-tools source=mise-or-tool-versions"',
    "  mise trust -a || true",
    "  mise install",
    "else",
    '  record_tooling "skip mise-declared-tools reason=no-mise-config"',
    "fi",
    'NODE_VERSION=""',
    'NODE_SOURCE=""',
    "if [ -f .node-version ]; then",
    '  NODE_VERSION="$(first_line_version .node-version)"',
    '  NODE_SOURCE=".node-version"',
    "elif [ -f .nvmrc ]; then",
    '  NODE_VERSION="$(first_line_version .nvmrc)"',
    '  NODE_SOURCE=".nvmrc"',
    "fi",
    "if [ -z \"$NODE_VERSION\" ] && [ -f package.json ]; then",
    '  VOLTA_NODE="$(json_value package.json volta.node | sed "s/^v//")"',
    '  if [ -n "$VOLTA_NODE" ]; then',
    '    NODE_VERSION="$VOLTA_NODE"',
    '    NODE_SOURCE="package.json volta.node"',
    "  fi",
    "fi",
    "if [ -z \"$NODE_VERSION\" ] && [ -f package.json ]; then",
    '  NODE_ENGINE="$(json_value package.json engines.node | sed "s/^v//")"',
    '  if [ -n "$NODE_ENGINE" ]; then',
    '    if is_exact_version "$NODE_ENGINE"; then',
    '      NODE_VERSION="$NODE_ENGINE"',
    '      NODE_SOURCE="package.json engines.node"',
    "    else",
    '      record_tooling "defer node $NODE_ENGINE reason=engines-node-range"',
    "    fi",
    "  fi",
    "fi",
    'if [ -n "$NODE_VERSION" ]; then',
    '  install_mise_tool node "$NODE_VERSION" "$NODE_SOURCE"',
    "else",
    '  record_tooling "skip node reason=no-exact-node-version"',
    "fi",
    'PACKAGE_MANAGER=""',
    "if [ -f package.json ]; then",
    '  PACKAGE_MANAGER="$(json_value package.json packageManager)"',
    "  if [ -z \"$PACKAGE_MANAGER\" ]; then",
    '    VOLTA_PNPM="$(json_value package.json volta.pnpm)"',
    '    VOLTA_YARN="$(json_value package.json volta.yarn)"',
    '    VOLTA_NPM="$(json_value package.json volta.npm)"',
    '    if [ -n "$VOLTA_PNPM" ]; then',
    '      PACKAGE_MANAGER="pnpm@$VOLTA_PNPM"',
    '    elif [ -n "$VOLTA_YARN" ]; then',
    '      PACKAGE_MANAGER="yarn@$VOLTA_YARN"',
    '    elif [ -n "$VOLTA_NPM" ]; then',
    '      PACKAGE_MANAGER="npm@$VOLTA_NPM"',
    "    fi",
    "  fi",
    "fi",
    'if [ -n "$PACKAGE_MANAGER" ]; then',
    '  log_tooling "Detected package manager $PACKAGE_MANAGER from package.json"',
    '  record_tooling "detect package-manager $PACKAGE_MANAGER source=package.json"',
    '  PM_NAME="$(printf "%s" "$PACKAGE_MANAGER" | cut -d@ -f1)"',
    '  PM_VERSION="$(printf "%s" "$PACKAGE_MANAGER" | cut -s -d@ -f2-)"',
    '  case "$PM_NAME" in',
    "    bun)",
    '      if [ -n "$PM_VERSION" ]; then',
    '        install_mise_tool bun "$PM_VERSION" "package.json packageManager"',
    "      elif has_cmd bun; then",
    '        record_tooling "use bun $(bun --version) source=existing"',
    "      else",
    '        record_tooling "defer bun reason=package-manager-has-no-version"',
    "      fi",
    "      ;;",
    "    pnpm|yarn)",
    "      if has_cmd corepack; then",
    "        corepack enable",
    '        if [ -n "$PM_VERSION" ]; then',
    '          log_tooling "Activating $PACKAGE_MANAGER through Corepack"',
    '          corepack prepare "$PACKAGE_MANAGER" --activate',
    '          record_tooling "activate $PACKAGE_MANAGER source=package.json"',
    "        else",
    '          record_tooling "defer $PM_NAME reason=package-manager-has-no-version"',
    "        fi",
    '      elif has_cmd npm && [ -n "$PM_VERSION" ]; then',
    '        log_tooling "Installing $PACKAGE_MANAGER through npm"',
    '        npm install -g "$PACKAGE_MANAGER"',
    '        record_tooling "install $PACKAGE_MANAGER source=package.json"',
    "      else",
    '        record_tooling "defer $PM_NAME reason=corepack-unavailable"',
    "      fi",
    "      ;;",
    "    npm)",
    '      if [ -n "$PM_VERSION" ] && has_cmd npm; then',
    '        log_tooling "Activating npm $PM_VERSION"',
    '        npm install -g "npm@$PM_VERSION"',
    '        record_tooling "install npm $PM_VERSION source=package.json"',
    "      else",
    '        record_tooling "use npm source=existing-or-node-default"',
    "      fi",
    "      ;;",
    "    *)",
    '      record_tooling "defer $PM_NAME reason=unsupported-package-manager"',
    "      ;;",
    "  esac",
    "else",
    "  if [ -f bun.lock ] || [ -f bun.lockb ]; then",
    '    record_tooling "defer bun reason=lockfile-without-packageManager-version"',
    "  elif [ -f pnpm-lock.yaml ]; then",
    '    record_tooling "defer pnpm reason=lockfile-without-packageManager-version"',
    "  elif [ -f yarn.lock ]; then",
    '    record_tooling "defer yarn reason=lockfile-without-packageManager-version"',
    "  elif [ -f package-lock.json ]; then",
    '    record_tooling "use npm reason=package-lock"',
    "  else",
    '    record_tooling "skip package-manager reason=no-package-manager-signal"',
    "  fi",
    "fi",
    "if [ -f .python-version ]; then",
    '  PYTHON_VERSION="$(first_line_version .python-version)"',
    '  install_mise_tool python "$PYTHON_VERSION" ".python-version"',
    "elif [ -f runtime.txt ]; then",
    '  PYTHON_VERSION="$(sed -n "s/^python-//p" runtime.txt | head -n1 | tr -d "[:space:]")"',
    '  if [ -n "$PYTHON_VERSION" ]; then',
    '    install_mise_tool python "$PYTHON_VERSION" "runtime.txt"',
    "  else",
    '    record_tooling "defer python reason=runtime-txt-without-python-version"',
    "  fi",
    "elif [ -f pyproject.toml ]; then",
    '  PYTHON_RANGE="$(awk -F= \'/^[[:space:]]*requires-python[[:space:]]*=/{gsub(/[[:space:]\\"\\047]/, "", $2); print $2; exit}\' pyproject.toml)"',
    '  if printf "%s" "$PYTHON_RANGE" | grep -Eq "^==v?[0-9]+([.][0-9]+){1,2}$"; then',
    '    PYTHON_VERSION="$(printf "%s" "$PYTHON_RANGE" | sed "s/^==//; s/^v//")"',
    '    install_mise_tool python "$PYTHON_VERSION" "pyproject.toml requires-python"',
    "  elif [ -n \"$PYTHON_RANGE\" ]; then",
    '    record_tooling "defer python $PYTHON_RANGE reason=requires-python-range"',
    "  else",
    '    record_tooling "defer python reason=pyproject-without-exact-python-version"',
    "  fi",
    "fi",
    "if [ -f .go-version ]; then",
    '  GO_VERSION="$(first_line_version .go-version)"',
    '  install_mise_tool go "$GO_VERSION" ".go-version"',
    "elif [ -f .goenv-version ]; then",
    '  GO_VERSION="$(first_line_version .goenv-version)"',
    '  install_mise_tool go "$GO_VERSION" ".goenv-version"',
    "elif [ -f go.mod ]; then",
    "  GO_VERSION=$(awk '/^toolchain go[0-9]/{sub(/^go/, \"\", $2); print $2; exit} /^go [0-9]/{print $2; exit}' go.mod)",
    '  install_mise_tool go "$GO_VERSION" "go.mod"',
    "fi",
    "if [ -f rust-toolchain.toml ]; then",
    "  RUST_VERSION=$(awk -F= '/^[[:space:]]*channel[[:space:]]*=/{gsub(/[[:space:]\"\\047]/, \"\", $2); print $2; exit}' rust-toolchain.toml)",
    '  install_mise_tool rust "$RUST_VERSION" "rust-toolchain.toml"',
    "elif [ -f rust-toolchain ]; then",
    '  RUST_VERSION="$(first_line_version rust-toolchain)"',
    '  install_mise_tool rust "$RUST_VERSION" "rust-toolchain"',
    "elif [ -f Cargo.toml ]; then",
    '  record_tooling "defer rust reason=Cargo.toml-without-rust-toolchain"',
    "fi",
    "if [ -f .ruby-version ]; then",
    '  RUBY_VERSION="$(first_line_version .ruby-version)"',
    '  install_mise_tool ruby "$RUBY_VERSION" ".ruby-version"',
    "elif [ -f Gemfile ]; then",
    "  RUBY_VERSION=$(awk '/^[[:space:]]*ruby[[:space:]]+\"[0-9]/{gsub(/[\",]/, \"\", $2); print $2; exit}' Gemfile)",
    '  if [ -n "$RUBY_VERSION" ]; then',
    '    install_mise_tool ruby "$RUBY_VERSION" "Gemfile ruby"',
    "  else",
    '    record_tooling "defer ruby reason=Gemfile-without-ruby-version"',
    "  fi",
    "fi",
    "if [ -f .java-version ]; then",
    '  JAVA_VERSION="$(first_line_version .java-version)"',
    '  install_mise_tool java "$JAVA_VERSION" ".java-version"',
    "elif [ -f .sdkmanrc ]; then",
    "  JAVA_VERSION=$(awk -F= '/^java=/{print $2; exit}' .sdkmanrc)",
    '  if [ -n "$JAVA_VERSION" ]; then',
    '    install_mise_tool java "$JAVA_VERSION" ".sdkmanrc"',
    "  elif [ -f pom.xml ] || [ -f build.gradle ] || [ -f build.gradle.kts ]; then",
    '    record_tooling "defer java reason=jvm-project-without-java-version"',
    "  fi",
    "elif [ -f pom.xml ] || [ -f build.gradle ] || [ -f build.gradle.kts ]; then",
    '  record_tooling "defer java reason=jvm-project-without-java-version"',
    "fi",
    "if [ -f global.json ]; then",
    '  DOTNET_VERSION="$(json_value global.json sdk.version)"',
    '  if [ -n "$DOTNET_VERSION" ]; then',
    '    install_mise_tool dotnet "$DOTNET_VERSION" "global.json sdk.version"',
    "  fi",
    "elif find . -maxdepth 2 \\( -name '*.sln' -o -name '*.csproj' \\) -print -quit | grep -q .; then",
    '  record_tooling "defer dotnet reason=dotnet-project-without-global-json"',
    "fi",
    "if [ -f .terraform-version ]; then",
    '  TERRAFORM_VERSION="$(first_line_version .terraform-version)"',
    '  install_mise_tool terraform "$TERRAFORM_VERSION" ".terraform-version"',
    "elif find . -maxdepth 3 -name '*.tf' -print -quit | grep -q .; then",
    '  record_tooling "defer terraform reason=terraform-files-without-terraform-version"',
    "fi",
    "if [ -f .tofu-version ]; then",
    '  TOFU_VERSION="$(first_line_version .tofu-version)"',
    '  install_mise_tool opentofu "$TOFU_VERSION" ".tofu-version"',
    "fi",
    "if [ -f .fvmrc ]; then",
    '  FLUTTER_VERSION="$(json_value .fvmrc flutter)"',
    '  if [ -z "$FLUTTER_VERSION" ]; then FLUTTER_VERSION="$(first_line_version .fvmrc)"; fi',
    '  install_mise_tool flutter "$FLUTTER_VERSION" ".fvmrc"',
    "elif [ -f pubspec.yaml ]; then",
    '  record_tooling "defer flutter-dart reason=pubspec-without-fvm-version"',
    "fi",
    "if [ -f .zig-version ]; then",
    '  ZIG_VERSION="$(first_line_version .zig-version)"',
    '  install_mise_tool zig "$ZIG_VERSION" ".zig-version"',
    "elif [ -f build.zig ] || [ -f build.zig.zon ]; then",
    '  record_tooling "defer zig reason=zig-project-without-zig-version"',
    "fi",
    "if [ -f .swift-version ]; then",
    '  SWIFT_VERSION="$(first_line_version .swift-version)"',
    '  install_mise_tool swift "$SWIFT_VERSION" ".swift-version"',
    "elif [ -f Package.swift ]; then",
    '  record_tooling "defer swift reason=Package.swift-without-swift-version"',
    "fi",
    "if [ -f .php-version ]; then",
    '  PHP_VERSION="$(first_line_version .php-version)"',
    '  install_mise_tool php "$PHP_VERSION" ".php-version"',
    "elif [ -f composer.json ]; then",
    '  record_tooling "defer php reason=composer-json-without-php-version"',
    "fi",
    "if [ -f deno.json ] || [ -f deno.jsonc ]; then",
    '  record_tooling "defer deno reason=deno-config-without-version"',
    "fi",
    "if [ -f flake.nix ] || [ -f shell.nix ] || [ -f default.nix ]; then",
    '  record_tooling "defer nix reason=nix-environment-detected"',
    "fi",
    "if [ -f .devcontainer/devcontainer.json ]; then",
    '  record_tooling "defer devcontainer reason=devcontainer-detected"',
    "fi",
    "if has_cmd mise; then mise reshim || true; fi",
    'log_tooling "Smart Tooling ready"',
    "cloudcode-tool doctor || true",
  ].join("\n")
}
